# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ad23903ea456431a6eda37712ee519b649e989188f72a0c3a1754c20c18c2a9711e4ee4727f983cbe4475e73ea0cec5d6caf36f3f05411f73397a4c822c720

test:
  secret_key_base: c26bef0ca6e2e058d40bb96d5fbbdccefbc8409c00477931b6a7a0781701175aa35cdbb86885c4ebdeded9204cd2e712d9895d2488cdd775b751ee096dcc8a43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
